version: "3.8"
services:
  # Control node used to manage 
  # the managed nodes
  control_node:
    container_name: control_node
    image: ansible/control_node:v1
    build:
      context: control_node
      dockerfile: Dockerfile
    ports:
      - "8541:22"

  # First managed node
  first_managed_node:
    container_name: first_managed_node
    image: ansible/managed_node:v1
    depends_on:
      - control_node
    build:
      context: managed_node
      dockerfile: Dockerfile

  # Second managed node
  second_managed_node:
    container_name: second_managed_node
    image: ansible/managed_node:v1
    depends_on:
      - control_node
    build:
      context: managed_node
      dockerfile: Dockerfile